@startuml
class BoosterConfigs <<sealed>> {
    - _id : string
    - _sprite : Sprite
    - _name : string
    - _value : float
    + Value : float <<get>>
    + ID : string <<get>>
    + Name : string <<get>>
    + Type : UniqItemsType <<get>>
    + Sprite : Sprite <<get>>
}
ScriptableObject <|-- BoosterConfigs
IUniq <|-- BoosterConfigs
@enduml
