@startuml
class DialogueBubble <<sealed>> {
    - _messageFld : TMP_Text
    - _confirmBtn : Button
    - _concreteHintBtn : Button
    - _canvas : Canvas
    - <<readonly>> _compositeDisposable : CompositeDisposable
    - _messAnimProcess : CancellationTokenSource
    - _activeOrder : Order
    + BubbleOpenedFlag : bool <<get>>
    - Awake() : void
    - OnDestroy() : void
    + <<async>> Activate(order:Order) : UniTask
    + Activate(showButtons:bool) : void
    + Deactivate() : void
    + <<async>> ExecuteMessFill(mess:string, cancellationToken:CancellationToken) : UniTask
}
MonoBehaviour <|-- DialogueBubble
@enduml
