@startuml
class DisappearanceAnimation <<sealed>> {
    - _image : Image
    - _canvasGroup : CanvasGroup
    - _duration : float
    - _ease : Ease
    + Tween : Tween <<get>>
    + Play(duration:float?) : void
}
MonoBehaviour <|-- DisappearanceAnimation
IAnimation <|-- DisappearanceAnimation
@enduml
