@startuml
class DumpAnimation <<sealed>> {
    - _valueFactor : float = 1
    - _curve : AnimationCurve
    - _axis : Vector3
    - _speedFactor : float = 1f
    - _originPos : Vector3
    - _delta : float
    - Awake() : void
    - OnAnimationUpdate() : void
}
MonoBehaviour <|-- DumpAnimation
@enduml
