@startuml
class EssenceBottleShader <<sealed>> {
    - _renderer : MeshRenderer
    - _fillRange : Vector2
    - _material : Material
    - _fillLevelID : int
    - _mainColorID : int
    - _additiveColorID : int
    - Awake() : void
    + SetProgress(progress:float) : void
    + SetColor(color:Color, addedColor:Color) : void
}
MonoBehaviour <|-- EssenceBottleShader
@enduml
