@startuml
class GameConfigProvider <<sealed>> <<partial>> {
    - _potionConfigs : PotionConfig[]
    - _plantConfigs : PlantConfig[]
    - _essenceConfigs : EssenceConfig[]
    - _boosterConfigs : BoosterConfigs[]
    - _customersConfiguration : CustomersConfiguration
    - _mixEssenceDictionary : MixEssenceVisualData[]
    - _craftRowsData : CraftRowsData[]
    - _staticData : PersistentGameData
    - _browser : Dictionary<string, IUniq>
    - _craftRowsSpriteBrowser : Dictionary<string, Sprite>
    - _goodCustomerFarewellWords : CustomerFarewellWord[]
    - _badCustomerFarewellWords : CustomerFarewellWord[]
    - _mixerUniqId : string
    - _gardenBugsBoosterId : string
    - _gardenWaterBoosterId : string
    - _gardenFertilizersBoosterId : string
    - _potionEssenceRestoreBoosterId : string
    - _gardenQuickHarvestBoosterId : string
    + UniqOrderCount : int <<get>>
    + UniqVisualCount : int <<get>>
    + UniqCustomerInfoCount : int <<get>>
    + StaticData : PersistentGameData <<get>>
    + Potions : IEnumerable<PotionConfig> <<get>>
    + AllEssencesIDs : IEnumerable<string> <<get>>
    + Orders : IEnumerable<Order> <<get>>
    + GoodCustomerFarewells : IEnumerable<CustomerFarewellWord> <<get>>
    + BadCustomerFarewells : IEnumerable<CustomerFarewellWord> <<get>>
    + MixerUniqId : string <<get>>
    + GardenBugsBoosterId : string <<get>>
    + GardenWaterBoosterId : string <<get>>
    + GardenFertilizersBoosterId : string <<get>>
    + PotionEssenceRestoreBoosterId : string <<get>>
    + GardenQuickHarvestBoosterId : string <<get>>
    + GetByID(id:string) : TType
    + TryDefineTypeByID(id:string) : UniqItemsType
    + GetRandomBasedOnWeight() : TType
    + GetRandomBasedOnWeightFarewell(goodnessFlag:bool) : CustomerFarewellWord
    + GetEssenceMixVisualData(essences:List<(string id, int amount)>) : MixEssenceVisualData
    + GetCraftRowForPotionID(id:string) : Sprite
    + GetSpriteByID(id:string) : Sprite
    - CreteBrowser() : void
    - CreateFarewellsCollections() : void
}
enum UniqItemsType {
    None= -1,
    Potion= 0,
    Essence= 1,
    Plant= 2,
    CustomerVisual= 3,
    CustomerInfo= 4,
    Order= 5,
    Booster= 6,
    CustomerFarewellWord= 7,
}
interface IUniq {
    ID : string <<get>>
    Name : string <<get>>
    Type : UniqItemsType <<get>>
    Sprite : Sprite <<get>>
}
class MixEssenceVisualData <<sealed>> {
    - _compoundData : PotionCompoundData[]
    - _sprite : Sprite
    - _color : Color
    + CompoundData : PotionCompoundData[] <<get>>
    + Sprite : Sprite <<get>>
    + Color : Color <<get>>
}
class CraftRowsData <<sealed>> {
    - _potionID : string
    - _sprite : Sprite
    + PotionID : string <<get>>
    + Sprite : Sprite <<get>>
}
ScriptableObject <|-- GameConfigProvider
@enduml
