@startuml
class GameplayCursor <<sealed>> {
    - _spriteRenderer : SpriteRenderer
    - _cursorLayerID : string = "Cursor"
    - _zPos : float
    + ProcessedItem : InteractiveObject <<get>>
    + HandleItem : InteractiveObject <<get>>
    + ItemID : string <<get>>
    + IsHoldNow : bool <<get>>
    + TargetSpriteLayerOrder : int <<get>>
    + CursorLayerID : string <<get>>
    + ZPos : float <<get>>
    + AttachItem(processedItem:InteractiveObject, id:string, handleItem:InteractiveObject) : void
    + DetachItem() : void
}
MonoBehaviour <|-- GameplayCursor
@enduml
