@startuml
class GardenBugsSurface <<sealed>> {
    - _bugs : Transform[]
    - _perspectiveScaleStart : Transform
    - _perspectiveScaleEnd : Transform
    - _bugsSurfaceSettings : GardenBugsSurfaceSettings
    - _activeFlag : bool = false
    - _bugsHandler : (Transform bug, BugDeltaData data)[]
    - Awake() : void
    + Init(surfaceSettings:GardenBugsSurfaceSettings) : void
    - UpdateBugsMovement() : void
}
class BugDeltaData {
    + movementDelta : float
    + direction : Vector3
    + rotationFactor : float
    + rotationDirection : int
    + returningToAreaFlag : bool
}
class GardenBugsSurfaceSettings <<sealed>> {
    - _movementCurve : AnimationCurve
    - _movementCurveTimeFactor : float = 2
    - _movementCurveSpeedFactor : float = 1
    - _randomRotationOffsetAfterLeaveOut : float = 5f
    - _rotationAlignFactor : float = 6f
    - _perspectiveScale : Vector2
    + MovementCurve : AnimationCurve <<get>>
    + MovementCurveTimeFactor : float <<get>>
    + MovementCurveSpeedFactor : float <<get>>
    + RandomRotationOffsetAfterLeaveOut : float <<get>>
    + RotationAlignFactor : float <<get>>
    + PerspectiveScale : Vector2 <<get>>
}
AnchoredArea <|-- GardenBugsSurface
GardenBugsSurface +-- BugDeltaData
GardenBugsSurface +-- GardenBugsSurfaceSettings
@enduml
