@startuml
class GifAnimation <<sealed>> {
    + Filename : string
    - _loopFlag : bool = false
    - _isImage : bool = false
    - _mFrames : List<Sprite>
    - _mFrameDelay : List<float>
    - _mCurFrame : int = 0
    - _mTime : float = 0.0f
    - _originSprite : Sprite
    - _originColor : Color
    - _spriteRenderer : SpriteRenderer
    - _image : Image
    - _updateSub : IDisposable
    - _oneLoopPlayed : UniTaskCompletionSource
    - Awake() : void
    + <<async>> Play(color:Color?) : UniTask
    + SetColor(color:Color) : void
    - UpdateGif() : void
    - ResetDelta() : void
    - SetSprite(sprite:Sprite) : void
}
MonoBehaviour <|-- GifAnimation
@enduml
