@startuml
!include .\\C.puml
!include .\\GameService.puml
!include .\\ScreenSizeAdapter.puml
!include .\\Customers\Customer.puml
!include .\\Customers\CustomerFarewellWord.puml
!include .\\Customers\CustomerFetcher.puml
!include .\\Customers\CustomersConfiguration.puml
!include .\\Customers\PollEntity.puml
!include .\\Customers\ShopConfigurationProvider.puml
!include .\\DATA\BoosterConfigs.puml
!include .\\DATA\GameConfigProvider.puml
!include .\\DATA\GameDataProviderTools.puml
!include .\\DATA\GameSettingsConfiguration.puml
!include .\\DATA\PersistentGameData.puml
!include .\\DiScopes\GameplayDiScope.puml
!include .\\DiScopes\GlobalDIScope.puml
!include .\\Garden\GameplayGardenState.puml
!include .\\Garden\GardenBugsSurface.puml
!include .\\Garden\GardenTool.puml
!include .\\Garden\SeedDummy.puml
!include .\\Hall\DialogueBubble.puml
!include .\\Hall\GameplayHallState.puml
!include .\\Hall\PotionDummy.puml
!include .\\Infrastructure\ConfigPather.puml
!include .\\Infrastructure\DumpAnimation.puml
!include .\\Infrastructure\E.puml
!include .\\Infrastructure\f.puml
!include .\\Infrastructure\GameScene.puml
!include .\\Infrastructure\GifAnimation.puml
!include .\\Infrastructure\IAnimation.puml
!include .\\Infrastructure\IntractableAnimation.puml
!include .\\Infrastructure\RotationAnimation.puml
!include .\\Infrastructure\SceneResolver.puml
!include .\\Infrastructure\STimeSpan.puml
!include .\\Input\AnchoredArea.puml
!include .\\Input\ColliderArea.puml
!include .\\Input\GameplayCursor.puml
!include .\\Input\SomeArea.puml
!include .\\MainGameplay\BoosterProcessor.puml
!include .\\MainGameplay\DayResultsUI.puml
!include .\\MainGameplay\GameplayData.puml
!include .\\MainGameplay\GameplayHudUI.puml
!include .\\MainGameplay\GameplayService.puml
!include .\\MainGameplay\GameplayUIContainer.puml
!include .\\MainGameplay\StartDayUI.puml
!include .\\MainGameplay\Timer.puml
!include .\\MainMenu\MainMenuBinder.puml
!include .\\MainMenu\MainMenuGameState.puml
!include .\\Potion\EssenceBottle.puml
!include .\\Potion\EssenceBottleShader.puml
!include .\\Potion\EssenceMixer.puml
!include .\\Potion\GameplayPotionState.puml
!include .\\Potion\MixerBase.puml
!include .\\Potion\PlantDummy.puml
!include .\\Potion\PotionCauldron.puml
!include .\\Potion\PotionMixData.puml
!include .\\Potion\TrashCan.puml
!include .\\Shop\ShopUI.puml
!include .\\Shop\ShopUIItem.puml
!include .\\Customers\_Data\CustomerInfo.puml
!include .\\Customers\_Data\CustomerVisual.puml
!include .\\Customers\_Data\Order.puml
!include .\\Garden\Data\GardenBedData.puml
!include .\\Garden\Data\PlantConfig.puml
!include .\\Garden\GardenBed\BedAreaGrowingState.puml
!include .\\Garden\GardenBed\GardenBedArea.puml
!include .\\Garden\GardenBed\GardenBedCell.puml
!include .\\Garden\GardenBed\HarvestBedAreaState.puml
!include .\\Garden\UI\GardenBedUI.puml
!include .\\Garden\UI\GardenPlantUIItem.puml
!include .\\Garden\UI\GardenUI.puml
!include .\\Infrastructure\DI\DIContainer.puml
!include .\\Infrastructure\DI\VContainerExtensions.puml
!include .\\Infrastructure\GameStructs\GameplaySceneState.puml
!include .\\Infrastructure\GameStructs\IConfiguration.puml
!include .\\Infrastructure\UI\AppearsAnimation.puml
!include .\\Infrastructure\UI\BasketUIElement.puml
!include .\\Infrastructure\UI\CurtainAnimation.puml
!include .\\Infrastructure\UI\DisappearanceAnimation.puml
!include .\\Infrastructure\UI\ItemDummy.puml
!include .\\Infrastructure\UI\PulledUIItem.puml
!include .\\Infrastructure\UI\ScrollPanel.puml
!include .\\Input\InteractiveObjsTypes\InteractiveObject.puml
!include .\\Input\InteractiveObjsTypes\ObjectKeeper.puml
!include .\\Input\Manager\InputManager.puml
!include .\\Input\Manager\PlayerInput.puml
!include .\\Potion\Data\EssenceConfig.puml
!include .\\Potion\Data\PotionConfig.puml
!include .\\Potion\UI\PotionCraftPartUIItem.puml
!include .\\Potion\UI\PotionPlantUIItem.puml
!include .\\Potion\UI\PotionRecipeUIItem.puml
!include .\\Potion\UI\PotionUI.puml
!include .\\Infrastructure\GameStructs\FSM\GlobalStateMachine.puml
!include .\\Infrastructure\GameStructs\FSM\States\IExitableGameState.puml
!include .\\Infrastructure\GameStructs\FSM\States\IGameState.puml
!include .\\Infrastructure\GameStructs\FSM\States\StateWithPayload.puml
@enduml
