@startuml
class IntractableAnimation <<sealed>> {
    - _duration : float = 1f
    - _strength : float = 10f
    - _vibrationsCounter : int = 20
    - _rotationFactor : float = 1
    - _scaleFactor : float = 0.1f
    - _positionFactor : float = 0f
    - _tween : Sequence
    # <<override>> OnAwake() : void
    + <<override>> ProcessInteractivity(inputAction:InputManager.InputAction) : void
}
InteractiveObject <|-- IntractableAnimation
@enduml
