@startuml
class MainMenuGameState <<sealed>> {
    - <<readonly>> _gameService : GameService
    - <<readonly>> _inputManager : InputManager
    - _mainMenuBinder : MainMenuBinder
    + MainMenuGameState(gameService:GameService, inputManager:InputManager)
    + Enter() : void
    + <<async>> StartGame() : UniTaskVoid
}
IGameState <|-- MainMenuGameState
@enduml
