@startuml
class MainMenuBinder <<sealed>> {
    - _mainMenuGameState : MainMenuGameState
    + SetHandler(mainMenuGameState:MainMenuGameState) : void
    + ForceStartGame() : void
}
MonoBehaviour <|-- MainMenuBinder
@enduml
