@startuml
class PersistentGameData <<sealed>> {
    - _day : int = 1
    - _items : List<string>
    - _coins : int
    + {static} Clone(reference:PersistentGameData) : PersistentGameData
    + AddItem(item:string) : void
    + UpdateItems(items:IEnumerable<string>) : void
    + IncreaseDay() : void
    + Deposit(amount:int) : void
    + Withdraw(amount:int) : void
    + Coins : int <<get>>
    + Day : int <<get>>
    + Items : IEnumerable<string> <<get>>
}
@enduml
