@startuml
class RotationAnimation <<sealed>> {
    - _valueFactor : float = 1
    - _axis : Vector3
    - _curve : AnimationCurve
    - _speedFactor : float = 1f
    - _originRotation : Quaternion
    - _delta : float
    - Awake() : void
    - OnAnimationUpdate() : void
}
MonoBehaviour <|-- RotationAnimation
@enduml
