@startuml
class ScrollPanel <<sealed>> {
    - _closeTrigger : PulledUIItem
    - _plantPanelAnimationCurve : AnimationCurve
    - _plantPanelAnimationOffset : Vector3
    - _plantPanelAnimationDuration : float
    - _UIItemPrefab : ScrollViewItem
    - _container : Transform
    - _scroll : ScrollRect
    - _intFlag : bool = false
    - _panelAnimationHandler : Tween
    - _panelStartAnimPos : Vector3
    - _panelEndAnimPos : Vector3
    - _panelOriginPos : Vector3
    - _isPanelOpening : bool
    - _currentAnimProgress : float
    - <<readonly>> _items : List<ScrollViewItem>
    + OnClosed : ReactiveCommand <<get>>
    - Awake() : void
    + OpenPanel() : void
    - OnDisable() : void
    + UpdateData(configs:IUniq[]) : void
    - UpdatePanelState(isOpenRequired:bool) : void
    - UpdatePanelAnim(t:float) : void
    - PanelHidePosition : Vector3 <<get>>
}
MonoBehaviour <|-- ScrollPanel
@enduml
