@startuml
class StartDayUI <<sealed>> {
    - _visualVariants : VisualVariant[]
    - _mainImages : Image[]
    - _sammyImages : Image[]
    - _sammyGraphics : Graphic[]
    - _bg : Image
    - _clothespin : Image
    - _dayTMP : TMP_Text
    - _appearsAnimation : AppearsAnimation
    - _disappearanceAnimation : DisappearanceAnimation
    + InitAndShow(day:int, needAnimation:bool) : void
    + Close() : void
}
class VisualVariant <<sealed>> {
    + Background : Sprite <<get>>
    + Clothespin : Sprite <<get>>
    + MainColor : Color <<get>>
    + SammyColor : Color <<get>>
}
MonoBehaviour <|-- StartDayUI
StartDayUI +-- VisualVariant
@enduml
