@startuml
class ComputerPersistentTest {
- {static} int id
- {static} DateBase dateBase
- {static} Computer computer
- {static} Technique technique
+ void isComputerAdd()
+ void isComputerUpdate()
+ void isComputerDeleted()
- boolean isItemExist(List<Technique>)
+ {static} void setup()
}
@enduml